services:
  - type: web
    name: streamlit-app
    env: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    region: oregon
    envVars:
      - key: PORT
        value: "8501"
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.address=0.0.0.0 --server.enableCORS=false --server.port=8501
